DROP TABLE IF EXISTS  "PUBLIC"."PRICES";

CREATE MEMORY TABLE "PUBLIC"."PRICES"(
    "ID" INTEGER NOT NULL,
    "BRAND_ID" INTEGER,
    "CURR" CHARACTER VARYING(255),
    "END_DATE" TIMESTAMP,
    "PRICE" DOUBLE PRECISION,
    "PRICE_LIST" INTEGER,
    "PRIORITY" INTEGER,
    "PRODUCT_ID" INTEGER,
    "START_DATE" TIMESTAMP,
    CONSTRAINT "CONSTRAINT_8" PRIMARY KEY("ID")
);

